# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdXf2YonAAVTfNjQO9E9oHkflpnQEemk
"""

# ============================
# CodeAlpha Task 2 - FAQ Chatbot
# ============================

# Install required library
!pip -q install scikit-learn

import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# -----------------------------
# FAQ Dataset
# -----------------------------

faq_data = [
    {"question":"What is Artificial Intelligence?","answer":"Artificial Intelligence is the simulation of human intelligence by machines."},
    {"question":"What is Machine Learning?","answer":"Machine Learning is a subset of AI that enables systems to learn from data."},
    {"question":"What is Deep Learning?","answer":"Deep Learning uses neural networks with many layers to solve complex problems."},
    {"question":"What is Python?","answer":"Python is a popular programming language used in AI and web development."},
    {"question":"Who created Python?","answer":"Python was created by Guido van Rossum."},
    {"question":"What is NLP?","answer":"Natural Language Processing enables computers to understand human language."},
    {"question":"What is OpenCV?","answer":"OpenCV is a computer vision library used for image and video processing."},
    {"question":"What is TensorFlow?","answer":"TensorFlow is Google's machine learning framework."},
    {"question":"What is Scikit-learn?","answer":"Scikit-learn is a Python library for machine learning."},
    {"question":"What is a chatbot?","answer":"A chatbot is a program that interacts with users through conversation."},
    {"question":"What is Data Science?","answer":"Data Science extracts insights from structured and unstructured data."},
    {"question":"What is Computer Vision?","answer":"Computer Vision enables computers to interpret images and videos."},
    {"question":"What is an Algorithm?","answer":"An algorithm is a step-by-step procedure to solve a problem."},
    {"question":"What is Cloud Computing?","answer":"Cloud Computing provides computing services over the internet."},
    {"question":"What is GitHub?","answer":"GitHub is a platform used for version control and collaboration."},
    {"question":"What is Google Colab?","answer":"Google Colab is an online Python notebook environment."},
    {"question":"What is Streamlit?","answer":"Streamlit helps build web applications using Python."},
    {"question":"What is SQL?","answer":"SQL is a language used to manage databases."},
    {"question":"What is an API?","answer":"An API allows different software applications to communicate."},
    {"question":"What is cybersecurity?","answer":"Cybersecurity protects systems and networks from digital attacks."},
    {"question":"What is a neural network?","answer":"A neural network is a model inspired by the human brain."},
    {"question":"What is supervised learning?","answer":"Supervised learning trains models using labeled data."},
    {"question":"What is unsupervised learning?","answer":"Unsupervised learning finds hidden patterns in unlabeled data."},
    {"question":"What is reinforcement learning?","answer":"Reinforcement learning learns through rewards and penalties."},
    {"question":"What is a database?","answer":"A database stores and organizes information."},
    {"question":"What is HTML?","answer":"HTML is used to create web pages."},
    {"question":"What is CSS?","answer":"CSS styles the appearance of web pages."},
    {"question":"What is JavaScript?","answer":"JavaScript adds interactivity to websites."},
    {"question":"What is programming?","answer":"Programming is the process of writing computer instructions."},
    {"question":"What is CodeAlpha?","answer":"CodeAlpha offers internship programs in software and AI."}
]

# Save JSON file
with open("faq.json","w") as f:
    json.dump(faq_data,f,indent=4)

# -----------------------------
# Load Data
# -----------------------------

with open("faq.json","r") as f:
    data=json.load(f)

questions=[item["question"] for item in data]
answers=[item["answer"] for item in data]

# TF-IDF Vectorization
vectorizer=TfidfVectorizer()
question_vectors=vectorizer.fit_transform(questions)

print("="*50)
print("🤖 CodeAlpha FAQ Chatbot")
print("Type 'exit' to quit.")
print("="*50)

# -----------------------------
# Chat Loop
# -----------------------------

while True:

    user=input("\nYou: ")

    if user.lower()=="exit":
        print("Bot: Goodbye!")
        break

    user_vector=vectorizer.transform([user])

    similarity=cosine_similarity(user_vector,question_vectors)

    best_match=similarity.argmax()
    confidence=similarity.max()

    if confidence>0.25:
        print("Bot:",answers[best_match])
    else:
        print("Bot: Sorry, I couldn't find a suitable answer.")