# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJHLp9IGFZcMUlKF9bvauEVnJLKMkTYD
"""

# ============================================================
# CodeAlpha Task 4 - Object Detection & Tracking
# ============================================================

!pip -q install ultralytics

from ultralytics import YOLO
from IPython.display import Video
import os

# Download sample video
!wget -O animals.mp4 https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4

# Load model
model = YOLO("yolov8n.pt")

# Run tracking
model.track(
    source="animals.mp4",
    save=True,
    persist=True,
    conf=0.3
)

# Find output video
output_video = "runs/detect/track/animals.mp4"

print("Done!")

Video(output_video, embed=True)